name: Build, Scan, Push to ECR

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  ECR_REPO_NAME: "my-app-repo"

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, product, user]
    outputs:
      sha: ${{ steps.sha.outputs.short }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get short SHA
        id: sha
        run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        id: build
        run: |
          IMAGE="${{ steps.login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ matrix.service }}-${{ steps.sha.outputs.short }}"
          docker build -t $IMAGE ./app/${{ matrix.service }}
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "$IMAGE" > image-${{ matrix.service }}.txt
        env:
          DOCKER_BUILDKIT: 1

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.49.1

      - name: Trivy scan (critical only)
        run: |
          trivy image \
            --severity CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            --scanners vuln \
            --timeout 5m \
            ${{ steps.build.outputs.image }}

      - name: Push Docker image
        run: |
          docker push ${{ steps.build.outputs.image }}

      - name: Upload image URI for service
        uses: actions/upload-artifact@v4
        with:
          name: image-uri-${{ matrix.service }}
          path: image-${{ matrix.service }}.txt

  merge-artifacts:
    runs-on: ubuntu-latest
    needs: build-scan-push
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: image-uri-*
          path: ./artifacts

      - name: Combine image URIs
        run: cat ./artifacts/image-uri-*/image-*.txt > image-uris.txt

      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-uris
          path: image-uris.txt
